version: '3'
name: hakhaton
services:
  summariser:
    container_name: meeting
    image: al1fe/meeting_summariser:v01.06
    ports:
      - 80:8000
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY